# Generated by Django 4.0.4 on 2022-12-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_service_is_active_alter_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='desc',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
