{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "6967d7de",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "from main.packages.transliterate import to_latin"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "571a08ae",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e70d57cd",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "52638462",
   "metadata": {},
   "outputs": [],
   "source": [
    "df1 = pd.read_excel('Бизаники.xlsx')\n",
    "df1.columns = ['name1', 'price1', 'company1', 'producer1']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "6e350346",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>name1</th>\n",
       "      <th>price1</th>\n",
       "      <th>company1</th>\n",
       "      <th>producer1</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>L-Виава р-р. д/и 1г/10 мл №10</td>\n",
       "      <td>76850.00</td>\n",
       "      <td>Wol</td>\n",
       "      <td>Mefar Ilac Sanayu A.S. Турция</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>L-Виава р-р. д/и 1г/5 мл №5</td>\n",
       "      <td>77500.00</td>\n",
       "      <td>Wol</td>\n",
       "      <td>Mefar Ilac Sanayu A.S. Турция</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>L-лизина эсцинат 0,1% 5 мл №10</td>\n",
       "      <td>150350.00</td>\n",
       "      <td>Wol</td>\n",
       "      <td>Галичфарм,Украина</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>L-Цет таб №100</td>\n",
       "      <td>143092.79</td>\n",
       "      <td>Wol</td>\n",
       "      <td>Kusum Healthcare, Индия</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Абинекс таб. 1 мг №8 (Каберголин)</td>\n",
       "      <td>176300.00</td>\n",
       "      <td>Wol</td>\n",
       "      <td>Aburaihon Pharmaceutical Co</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1052</th>\n",
       "      <td>Медотилин р-р. д/и. 1000мг/4мл №3</td>\n",
       "      <td>130090.00</td>\n",
       "      <td>Wol</td>\n",
       "      <td>Mefar Ilac Sanayu A.S. Турция</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1053</th>\n",
       "      <td>Медролгин р-р. д/и. амп. 30 мг/мл №5</td>\n",
       "      <td>33300.00</td>\n",
       "      <td>Wol</td>\n",
       "      <td>Pharma Vision Sanayi ve Ticharet A.S .Турция</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1054</th>\n",
       "      <td>Мезакар таб. 200 мг №50</td>\n",
       "      <td>34000.00</td>\n",
       "      <td>Wol</td>\n",
       "      <td>Kusum Healthcare, Индия</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1055</th>\n",
       "      <td>Мезакар таб. 400 мг №50</td>\n",
       "      <td>52350.00</td>\n",
       "      <td>Wol</td>\n",
       "      <td>Kusum Healthcare, Индия</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1056</th>\n",
       "      <td>Мезатон р-р. 10мг/мл 1мл амп. №10</td>\n",
       "      <td>12230.00</td>\n",
       "      <td>Wol</td>\n",
       "      <td>Здоровье , Украина</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>1057 rows × 4 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                                     name1     price1 company1  \\\n",
       "0            L-Виава р-р. д/и 1г/10 мл №10   76850.00      Wol   \n",
       "1              L-Виава р-р. д/и 1г/5 мл №5   77500.00      Wol   \n",
       "2           L-лизина эсцинат 0,1% 5 мл №10  150350.00      Wol   \n",
       "3                           L-Цет таб №100  143092.79      Wol   \n",
       "4        Абинекс таб. 1 мг №8 (Каберголин)  176300.00      Wol   \n",
       "...                                    ...        ...      ...   \n",
       "1052     Медотилин р-р. д/и. 1000мг/4мл №3  130090.00      Wol   \n",
       "1053  Медролгин р-р. д/и. амп. 30 мг/мл №5   33300.00      Wol   \n",
       "1054               Мезакар таб. 200 мг №50   34000.00      Wol   \n",
       "1055               Мезакар таб. 400 мг №50   52350.00      Wol   \n",
       "1056     Мезатон р-р. 10мг/мл 1мл амп. №10   12230.00      Wol   \n",
       "\n",
       "                                         producer1  \n",
       "0                    Mefar Ilac Sanayu A.S. Турция  \n",
       "1                    Mefar Ilac Sanayu A.S. Турция  \n",
       "2                                Галичфарм,Украина  \n",
       "3                          Kusum Healthcare, Индия  \n",
       "4                      Aburaihon Pharmaceutical Co  \n",
       "...                                            ...  \n",
       "1052                 Mefar Ilac Sanayu A.S. Турция  \n",
       "1053  Pharma Vision Sanayi ve Ticharet A.S .Турция  \n",
       "1054                       Kusum Healthcare, Индия  \n",
       "1055                       Kusum Healthcare, Индия  \n",
       "1056                            Здоровье , Украина  \n",
       "\n",
       "[1057 rows x 4 columns]"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "a253bd9e",
   "metadata": {},
   "outputs": [],
   "source": [
    "df2 = pd.read_excel(\"Волфарм1.xlsx\")\n",
    "df2.columns = ['name2', 'price2', 'date2', 'producer2']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "9982c244",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>name2</th>\n",
       "      <th>price2</th>\n",
       "      <th>date2</th>\n",
       "      <th>producer2</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>L-Цет таб №100</td>\n",
       "      <td>138800.0063</td>\n",
       "      <td>45474</td>\n",
       "      <td>Kusum Healthcare, Индия</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Q10 МАКС капс. №40</td>\n",
       "      <td>106690.3000</td>\n",
       "      <td>45352</td>\n",
       "      <td>ООО \"PHARMAXX INTERNATIONAL\"</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Абинекс таб. 1 мг №8 (Каберголин)</td>\n",
       "      <td>171011.0000</td>\n",
       "      <td>45078</td>\n",
       "      <td>Aburaihon Pharmaceutical Co</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Авикарнитин р-р. 100мг/100мл №1 (Левокарнитин)</td>\n",
       "      <td>81305.4000</td>\n",
       "      <td>45261</td>\n",
       "      <td>Марс Ремедис Пвт.ЛТД</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Авирол-С капс. №12 (Грипп+ОРЗ)</td>\n",
       "      <td>31437.7000</td>\n",
       "      <td>45017</td>\n",
       "      <td>Ника Фарм</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1169</th>\n",
       "      <td>Нистатин супп.ваг. 500000 ЕД №10</td>\n",
       "      <td>15371.5900</td>\n",
       "      <td>45231</td>\n",
       "      <td>Биосинтез ОАО, Россия</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1170</th>\n",
       "      <td>Нистатин таб. 500000 ЕД №20</td>\n",
       "      <td>7711.5000</td>\n",
       "      <td>45474</td>\n",
       "      <td>Белмедпрепараты,РУП Борисовский завод</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1171</th>\n",
       "      <td>Нистатин таб. 500000 ЕД №20</td>\n",
       "      <td>7711.5000</td>\n",
       "      <td>45047</td>\n",
       "      <td>Биосинтез ОАО, Россия</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1172</th>\n",
       "      <td>Нитазод пор. д/п. сусп. 100мг/5мл 60мл</td>\n",
       "      <td>48422.4000</td>\n",
       "      <td>44713</td>\n",
       "      <td>Al Andalous for Pharmaceutical Ind, Египет</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1173</th>\n",
       "      <td>НИТАСПЕКТ таб. 500 мг №20</td>\n",
       "      <td>69258.0000</td>\n",
       "      <td>45658</td>\n",
       "      <td>Egyptian Group for Pharmaceutical Industries, ...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>1174 rows × 4 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                                               name2       price2  date2  \\\n",
       "0                                     L-Цет таб №100  138800.0063  45474   \n",
       "1                                 Q10 МАКС капс. №40  106690.3000  45352   \n",
       "2                  Абинекс таб. 1 мг №8 (Каберголин)  171011.0000  45078   \n",
       "3     Авикарнитин р-р. 100мг/100мл №1 (Левокарнитин)   81305.4000  45261   \n",
       "4                     Авирол-С капс. №12 (Грипп+ОРЗ)   31437.7000  45017   \n",
       "...                                              ...          ...    ...   \n",
       "1169                Нистатин супп.ваг. 500000 ЕД №10   15371.5900  45231   \n",
       "1170                     Нистатин таб. 500000 ЕД №20    7711.5000  45474   \n",
       "1171                     Нистатин таб. 500000 ЕД №20    7711.5000  45047   \n",
       "1172          Нитазод пор. д/п. сусп. 100мг/5мл 60мл   48422.4000  44713   \n",
       "1173                       НИТАСПЕКТ таб. 500 мг №20   69258.0000  45658   \n",
       "\n",
       "                                              producer2  \n",
       "0                               Kusum Healthcare, Индия  \n",
       "1                          ООО \"PHARMAXX INTERNATIONAL\"  \n",
       "2                           Aburaihon Pharmaceutical Co  \n",
       "3                                  Марс Ремедис Пвт.ЛТД  \n",
       "4                                             Ника Фарм  \n",
       "...                                                 ...  \n",
       "1169                              Биосинтез ОАО, Россия  \n",
       "1170              Белмедпрепараты,РУП Борисовский завод  \n",
       "1171                              Биосинтез ОАО, Россия  \n",
       "1172         Al Andalous for Pharmaceutical Ind, Египет  \n",
       "1173  Egyptian Group for Pharmaceutical Industries, ...  \n",
       "\n",
       "[1174 rows x 4 columns]"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "99c3abbe",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'Moyo sudno na vozdushnoj podushke polno ugrej'"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import cyrtranslit\n",
    "cyrtranslit.to_latin('Моё судно на воздушной подушке полно угрей', 'ru')\n",
    "#def to_latin(text):\n",
    " #   return cyrtranslit.to_latin(text)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "f1fed50a",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'Мoyo sudno na vozdushnoy podushke polno ugrey'"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "to_latin('Моё судно на воздушной подушке полно угрей')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "8967c021",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>name1</th>\n",
       "      <th>price1</th>\n",
       "      <th>company1</th>\n",
       "      <th>producer1</th>\n",
       "      <th>name_latin</th>\n",
       "      <th>producer_latin</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>L-Виава р-р. д/и 1г/10 мл №10</td>\n",
       "      <td>76850.00</td>\n",
       "      <td>Wol</td>\n",
       "      <td>Mefar Ilac Sanayu A.S. Турция</td>\n",
       "      <td>L-Вiava r-r. d/i 1g/10 ml №10</td>\n",
       "      <td>Mefar Ilac Sanayu A.S. Тurtsiya</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>L-Виава р-р. д/и 1г/5 мл №5</td>\n",
       "      <td>77500.00</td>\n",
       "      <td>Wol</td>\n",
       "      <td>Mefar Ilac Sanayu A.S. Турция</td>\n",
       "      <td>L-Вiava r-r. d/i 1g/5 ml №5</td>\n",
       "      <td>Mefar Ilac Sanayu A.S. Тurtsiya</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>L-лизина эсцинат 0,1% 5 мл №10</td>\n",
       "      <td>150350.00</td>\n",
       "      <td>Wol</td>\n",
       "      <td>Галичфарм,Украина</td>\n",
       "      <td>L-lizina estsinat 0,1% 5 ml №10</td>\n",
       "      <td>Гalichfarm,Уkraina</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>L-Цет таб №100</td>\n",
       "      <td>143092.79</td>\n",
       "      <td>Wol</td>\n",
       "      <td>Kusum Healthcare, Индия</td>\n",
       "      <td>L-Set tab №100</td>\n",
       "      <td>Kusum Healthcare, Иndiya</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Абинекс таб. 1 мг №8 (Каберголин)</td>\n",
       "      <td>176300.00</td>\n",
       "      <td>Wol</td>\n",
       "      <td>Aburaihon Pharmaceutical Co</td>\n",
       "      <td>Аbineks tab. 1 mg №8 (Кabergolin)</td>\n",
       "      <td>Aburaihon Pharmaceutical Co</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1052</th>\n",
       "      <td>Медотилин р-р. д/и. 1000мг/4мл №3</td>\n",
       "      <td>130090.00</td>\n",
       "      <td>Wol</td>\n",
       "      <td>Mefar Ilac Sanayu A.S. Турция</td>\n",
       "      <td>Мedotilin r-r. d/i. 1000mg/4ml №3</td>\n",
       "      <td>Mefar Ilac Sanayu A.S. Тurtsiya</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1053</th>\n",
       "      <td>Медролгин р-р. д/и. амп. 30 мг/мл №5</td>\n",
       "      <td>33300.00</td>\n",
       "      <td>Wol</td>\n",
       "      <td>Pharma Vision Sanayi ve Ticharet A.S .Турция</td>\n",
       "      <td>Мedrolgin r-r. d/i. amp. 30 mg/ml №5</td>\n",
       "      <td>Pharma Vision Sanayi ve Ticharet A.S .Тurtsiya</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1054</th>\n",
       "      <td>Мезакар таб. 200 мг №50</td>\n",
       "      <td>34000.00</td>\n",
       "      <td>Wol</td>\n",
       "      <td>Kusum Healthcare, Индия</td>\n",
       "      <td>Мezakar tab. 200 mg №50</td>\n",
       "      <td>Kusum Healthcare, Иndiya</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1055</th>\n",
       "      <td>Мезакар таб. 400 мг №50</td>\n",
       "      <td>52350.00</td>\n",
       "      <td>Wol</td>\n",
       "      <td>Kusum Healthcare, Индия</td>\n",
       "      <td>Мezakar tab. 400 mg №50</td>\n",
       "      <td>Kusum Healthcare, Иndiya</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1056</th>\n",
       "      <td>Мезатон р-р. 10мг/мл 1мл амп. №10</td>\n",
       "      <td>12230.00</td>\n",
       "      <td>Wol</td>\n",
       "      <td>Здоровье , Украина</td>\n",
       "      <td>Мezaton r-r. 10mg/ml 1ml amp. №10</td>\n",
       "      <td>Зdorove , Уkraina</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>1057 rows × 6 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                                     name1     price1 company1  \\\n",
       "0            L-Виава р-р. д/и 1г/10 мл №10   76850.00      Wol   \n",
       "1              L-Виава р-р. д/и 1г/5 мл №5   77500.00      Wol   \n",
       "2           L-лизина эсцинат 0,1% 5 мл №10  150350.00      Wol   \n",
       "3                           L-Цет таб №100  143092.79      Wol   \n",
       "4        Абинекс таб. 1 мг №8 (Каберголин)  176300.00      Wol   \n",
       "...                                    ...        ...      ...   \n",
       "1052     Медотилин р-р. д/и. 1000мг/4мл №3  130090.00      Wol   \n",
       "1053  Медролгин р-р. д/и. амп. 30 мг/мл №5   33300.00      Wol   \n",
       "1054               Мезакар таб. 200 мг №50   34000.00      Wol   \n",
       "1055               Мезакар таб. 400 мг №50   52350.00      Wol   \n",
       "1056     Мезатон р-р. 10мг/мл 1мл амп. №10   12230.00      Wol   \n",
       "\n",
       "                                         producer1  \\\n",
       "0                    Mefar Ilac Sanayu A.S. Турция   \n",
       "1                    Mefar Ilac Sanayu A.S. Турция   \n",
       "2                                Галичфарм,Украина   \n",
       "3                          Kusum Healthcare, Индия   \n",
       "4                      Aburaihon Pharmaceutical Co   \n",
       "...                                            ...   \n",
       "1052                 Mefar Ilac Sanayu A.S. Турция   \n",
       "1053  Pharma Vision Sanayi ve Ticharet A.S .Турция   \n",
       "1054                       Kusum Healthcare, Индия   \n",
       "1055                       Kusum Healthcare, Индия   \n",
       "1056                            Здоровье , Украина   \n",
       "\n",
       "                                name_latin  \\\n",
       "0            L-Вiava r-r. d/i 1g/10 ml №10   \n",
       "1              L-Вiava r-r. d/i 1g/5 ml №5   \n",
       "2          L-lizina estsinat 0,1% 5 ml №10   \n",
       "3                           L-Set tab №100   \n",
       "4        Аbineks tab. 1 mg №8 (Кabergolin)   \n",
       "...                                    ...   \n",
       "1052     Мedotilin r-r. d/i. 1000mg/4ml №3   \n",
       "1053  Мedrolgin r-r. d/i. amp. 30 mg/ml №5   \n",
       "1054               Мezakar tab. 200 mg №50   \n",
       "1055               Мezakar tab. 400 mg №50   \n",
       "1056     Мezaton r-r. 10mg/ml 1ml amp. №10   \n",
       "\n",
       "                                      producer_latin  \n",
       "0                    Mefar Ilac Sanayu A.S. Тurtsiya  \n",
       "1                    Mefar Ilac Sanayu A.S. Тurtsiya  \n",
       "2                                 Гalichfarm,Уkraina  \n",
       "3                           Kusum Healthcare, Иndiya  \n",
       "4                        Aburaihon Pharmaceutical Co  \n",
       "...                                              ...  \n",
       "1052                 Mefar Ilac Sanayu A.S. Тurtsiya  \n",
       "1053  Pharma Vision Sanayi ve Ticharet A.S .Тurtsiya  \n",
       "1054                        Kusum Healthcare, Иndiya  \n",
       "1055                        Kusum Healthcare, Иndiya  \n",
       "1056                               Зdorove , Уkraina  \n",
       "\n",
       "[1057 rows x 6 columns]"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df1['name_latin'] = df1['name1'].apply(to_latin)\n",
    "df1['producer_latin'] = df1['producer1'].apply(to_latin)\n",
    "df1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "a6b265fb",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>name2</th>\n",
       "      <th>price2</th>\n",
       "      <th>date2</th>\n",
       "      <th>producer2</th>\n",
       "      <th>name_latin</th>\n",
       "      <th>producer_latin</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>L-Цет таб №100</td>\n",
       "      <td>138800.0063</td>\n",
       "      <td>45474</td>\n",
       "      <td>Kusum Healthcare, Индия</td>\n",
       "      <td>L-Set tab №100</td>\n",
       "      <td>Kusum Healthcare, Иndiya</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Q10 МАКС капс. №40</td>\n",
       "      <td>106690.3000</td>\n",
       "      <td>45352</td>\n",
       "      <td>ООО \"PHARMAXX INTERNATIONAL\"</td>\n",
       "      <td>Q10 МАКС kaps. №40</td>\n",
       "      <td>ООО \"PHARMAXX INTERNATIONAL\"</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Абинекс таб. 1 мг №8 (Каберголин)</td>\n",
       "      <td>171011.0000</td>\n",
       "      <td>45078</td>\n",
       "      <td>Aburaihon Pharmaceutical Co</td>\n",
       "      <td>Аbineks tab. 1 mg №8 (Кabergolin)</td>\n",
       "      <td>Aburaihon Pharmaceutical Co</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Авикарнитин р-р. 100мг/100мл №1 (Левокарнитин)</td>\n",
       "      <td>81305.4000</td>\n",
       "      <td>45261</td>\n",
       "      <td>Марс Ремедис Пвт.ЛТД</td>\n",
       "      <td>Аvikarnitin r-r. 100mg/100ml №1 (Лevokarnitin)</td>\n",
       "      <td>Мars Рemedis Пvt.ЛТД</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Авирол-С капс. №12 (Грипп+ОРЗ)</td>\n",
       "      <td>31437.7000</td>\n",
       "      <td>45017</td>\n",
       "      <td>Ника Фарм</td>\n",
       "      <td>Аvirol-С kaps. №12 (Гripp+ОРЗ)</td>\n",
       "      <td>Нika Фarm</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1169</th>\n",
       "      <td>Нистатин супп.ваг. 500000 ЕД №10</td>\n",
       "      <td>15371.5900</td>\n",
       "      <td>45231</td>\n",
       "      <td>Биосинтез ОАО, Россия</td>\n",
       "      <td>Нistatin supp.vag. 500000 eД №10</td>\n",
       "      <td>Бiosintez ОАО, Рossiya</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1170</th>\n",
       "      <td>Нистатин таб. 500000 ЕД №20</td>\n",
       "      <td>7711.5000</td>\n",
       "      <td>45474</td>\n",
       "      <td>Белмедпрепараты,РУП Борисовский завод</td>\n",
       "      <td>Нistatin tab. 500000 eД №20</td>\n",
       "      <td>Бelmedpreparati,РУП Бorisovskiy zavod</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1171</th>\n",
       "      <td>Нистатин таб. 500000 ЕД №20</td>\n",
       "      <td>7711.5000</td>\n",
       "      <td>45047</td>\n",
       "      <td>Биосинтез ОАО, Россия</td>\n",
       "      <td>Нistatin tab. 500000 eД №20</td>\n",
       "      <td>Бiosintez ОАО, Рossiya</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1172</th>\n",
       "      <td>Нитазод пор. д/п. сусп. 100мг/5мл 60мл</td>\n",
       "      <td>48422.4000</td>\n",
       "      <td>44713</td>\n",
       "      <td>Al Andalous for Pharmaceutical Ind, Египет</td>\n",
       "      <td>Нitazod por. d/p. susp. 100mg/5ml 60ml</td>\n",
       "      <td>Al Andalous for Pharmaceutical Ind, egipet</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1173</th>\n",
       "      <td>НИТАСПЕКТ таб. 500 мг №20</td>\n",
       "      <td>69258.0000</td>\n",
       "      <td>45658</td>\n",
       "      <td>Egyptian Group for Pharmaceutical Industries, ...</td>\n",
       "      <td>НИТАСПЕКТ tab. 500 mg №20</td>\n",
       "      <td>Egyptian Group for Pharmaceutical Industries, ...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>1174 rows × 6 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                                               name2       price2  date2  \\\n",
       "0                                     L-Цет таб №100  138800.0063  45474   \n",
       "1                                 Q10 МАКС капс. №40  106690.3000  45352   \n",
       "2                  Абинекс таб. 1 мг №8 (Каберголин)  171011.0000  45078   \n",
       "3     Авикарнитин р-р. 100мг/100мл №1 (Левокарнитин)   81305.4000  45261   \n",
       "4                     Авирол-С капс. №12 (Грипп+ОРЗ)   31437.7000  45017   \n",
       "...                                              ...          ...    ...   \n",
       "1169                Нистатин супп.ваг. 500000 ЕД №10   15371.5900  45231   \n",
       "1170                     Нистатин таб. 500000 ЕД №20    7711.5000  45474   \n",
       "1171                     Нистатин таб. 500000 ЕД №20    7711.5000  45047   \n",
       "1172          Нитазод пор. д/п. сусп. 100мг/5мл 60мл   48422.4000  44713   \n",
       "1173                       НИТАСПЕКТ таб. 500 мг №20   69258.0000  45658   \n",
       "\n",
       "                                              producer2  \\\n",
       "0                               Kusum Healthcare, Индия   \n",
       "1                          ООО \"PHARMAXX INTERNATIONAL\"   \n",
       "2                           Aburaihon Pharmaceutical Co   \n",
       "3                                  Марс Ремедис Пвт.ЛТД   \n",
       "4                                             Ника Фарм   \n",
       "...                                                 ...   \n",
       "1169                              Биосинтез ОАО, Россия   \n",
       "1170              Белмедпрепараты,РУП Борисовский завод   \n",
       "1171                              Биосинтез ОАО, Россия   \n",
       "1172         Al Andalous for Pharmaceutical Ind, Египет   \n",
       "1173  Egyptian Group for Pharmaceutical Industries, ...   \n",
       "\n",
       "                                          name_latin  \\\n",
       "0                                     L-Set tab №100   \n",
       "1                                 Q10 МАКС kaps. №40   \n",
       "2                  Аbineks tab. 1 mg №8 (Кabergolin)   \n",
       "3     Аvikarnitin r-r. 100mg/100ml №1 (Лevokarnitin)   \n",
       "4                     Аvirol-С kaps. №12 (Гripp+ОРЗ)   \n",
       "...                                              ...   \n",
       "1169                Нistatin supp.vag. 500000 eД №10   \n",
       "1170                     Нistatin tab. 500000 eД №20   \n",
       "1171                     Нistatin tab. 500000 eД №20   \n",
       "1172          Нitazod por. d/p. susp. 100mg/5ml 60ml   \n",
       "1173                       НИТАСПЕКТ tab. 500 mg №20   \n",
       "\n",
       "                                         producer_latin  \n",
       "0                              Kusum Healthcare, Иndiya  \n",
       "1                          ООО \"PHARMAXX INTERNATIONAL\"  \n",
       "2                           Aburaihon Pharmaceutical Co  \n",
       "3                                  Мars Рemedis Пvt.ЛТД  \n",
       "4                                             Нika Фarm  \n",
       "...                                                 ...  \n",
       "1169                             Бiosintez ОАО, Рossiya  \n",
       "1170              Бelmedpreparati,РУП Бorisovskiy zavod  \n",
       "1171                             Бiosintez ОАО, Рossiya  \n",
       "1172         Al Andalous for Pharmaceutical Ind, egipet  \n",
       "1173  Egyptian Group for Pharmaceutical Industries, ...  \n",
       "\n",
       "[1174 rows x 6 columns]"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df2['name_latin'] = df2['name2'].apply(to_latin)\n",
    "df2['producer_latin'] = df2['producer2'].apply(to_latin)\n",
    "df2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2e7420a1",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5aa28989",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f2c8c08b",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0ada4717",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3f4236de",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "f61c7734",
   "metadata": {},
   "outputs": [],
   "source": [
    "df3 = pd.DataFrame()\n",
    "for i in df1.index:\n",
    "    df3 = pd.concat([df3, df2.loc[(df1.loc[i, 'name_latin'] == df2['name_latin']) & (df1.loc[i, 'producer_latin'] == df2['producer_latin']), ['name2', 'producer2', 'name_latin', 'producer_latin']]], axis=0)\n",
    "    #df3 = pd.concat([df3, df2.loc[(df1.loc[i, 'name1'] == df2['name2']) & (df1.loc[i, 'producer1'] == df2['producer2']), ['name2', 'producer2']]], axis=0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "86a08f0d",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>name2</th>\n",
       "      <th>producer2</th>\n",
       "      <th>name_latin</th>\n",
       "      <th>producer_latin</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>L-Цет таб №100</td>\n",
       "      <td>Kusum Healthcare, Индия</td>\n",
       "      <td>L-Set tab №100</td>\n",
       "      <td>Kusum Healthcare, Иndiya</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Абинекс таб. 1 мг №8 (Каберголин)</td>\n",
       "      <td>Aburaihon Pharmaceutical Co</td>\n",
       "      <td>Аbineks tab. 1 mg №8 (Кabergolin)</td>\n",
       "      <td>Aburaihon Pharmaceutical Co</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>Автория таб. 25 мг №30</td>\n",
       "      <td>Psychotropics India Limited, Индия</td>\n",
       "      <td>Аvtoriya tab. 25 mg №30</td>\n",
       "      <td>Psychotropics India Limited, Иndiya</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>Адазал сусп. 100мг/5мг.30мл №1</td>\n",
       "      <td>BIOGEN</td>\n",
       "      <td>Аdazal susp. 100mg/5mg.30ml №1</td>\n",
       "      <td>BIOGEN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>Адемта лиоф. д/и. 400мг/5мл №5</td>\n",
       "      <td>Сертус</td>\n",
       "      <td>Аdemta liof. d/i. 400mg/5ml №5</td>\n",
       "      <td>Сertus</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>997</th>\n",
       "      <td>Медитрол капс. 0,25 №30</td>\n",
       "      <td>Мега Лайфсайнсиз ЛТД, Австралия</td>\n",
       "      <td>Мeditrol kaps. 0,25 №30</td>\n",
       "      <td>Мega Лayfsaynsiz ЛТД, Аvstraliya</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>998</th>\n",
       "      <td>Медолопрам таб. 10 мг №28</td>\n",
       "      <td>World Medicine Ilac San. Ve Tic. A.S. Турция</td>\n",
       "      <td>Мedolopram tab. 10 mg №28</td>\n",
       "      <td>World Medicine Ilac San. Ve Tic. A.S. Тurtsiya</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>999</th>\n",
       "      <td>Медотилин капс. 400 мг №14</td>\n",
       "      <td>World Medicine Ilac San. Ve Tic. A.S. Турция</td>\n",
       "      <td>Мedotilin kaps. 400 mg №14</td>\n",
       "      <td>World Medicine Ilac San. Ve Tic. A.S. Тurtsiya</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1000</th>\n",
       "      <td>Мезакар таб. 200 мг №50</td>\n",
       "      <td>Kusum Healthcare, Индия</td>\n",
       "      <td>Мezakar tab. 200 mg №50</td>\n",
       "      <td>Kusum Healthcare, Иndiya</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1002</th>\n",
       "      <td>Мезатон р-р. 10мг/мл 1мл амп. №10</td>\n",
       "      <td>Здоровье , Украина</td>\n",
       "      <td>Мezaton r-r. 10mg/ml 1ml amp. №10</td>\n",
       "      <td>Зdorove , Уkraina</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>812 rows × 4 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                                  name2  \\\n",
       "0                        L-Цет таб №100   \n",
       "2     Абинекс таб. 1 мг №8 (Каберголин)   \n",
       "5                Автория таб. 25 мг №30   \n",
       "6        Адазал сусп. 100мг/5мг.30мл №1   \n",
       "7        Адемта лиоф. д/и. 400мг/5мл №5   \n",
       "...                                 ...   \n",
       "997             Медитрол капс. 0,25 №30   \n",
       "998           Медолопрам таб. 10 мг №28   \n",
       "999          Медотилин капс. 400 мг №14   \n",
       "1000            Мезакар таб. 200 мг №50   \n",
       "1002  Мезатон р-р. 10мг/мл 1мл амп. №10   \n",
       "\n",
       "                                         producer2  \\\n",
       "0                          Kusum Healthcare, Индия   \n",
       "2                      Aburaihon Pharmaceutical Co   \n",
       "5               Psychotropics India Limited, Индия   \n",
       "6                                           BIOGEN   \n",
       "7                                           Сертус   \n",
       "...                                            ...   \n",
       "997                Мега Лайфсайнсиз ЛТД, Австралия   \n",
       "998   World Medicine Ilac San. Ve Tic. A.S. Турция   \n",
       "999   World Medicine Ilac San. Ve Tic. A.S. Турция   \n",
       "1000                       Kusum Healthcare, Индия   \n",
       "1002                            Здоровье , Украина   \n",
       "\n",
       "                             name_latin  \\\n",
       "0                        L-Set tab №100   \n",
       "2     Аbineks tab. 1 mg №8 (Кabergolin)   \n",
       "5               Аvtoriya tab. 25 mg №30   \n",
       "6        Аdazal susp. 100mg/5mg.30ml №1   \n",
       "7        Аdemta liof. d/i. 400mg/5ml №5   \n",
       "...                                 ...   \n",
       "997             Мeditrol kaps. 0,25 №30   \n",
       "998           Мedolopram tab. 10 mg №28   \n",
       "999          Мedotilin kaps. 400 mg №14   \n",
       "1000            Мezakar tab. 200 mg №50   \n",
       "1002  Мezaton r-r. 10mg/ml 1ml amp. №10   \n",
       "\n",
       "                                      producer_latin  \n",
       "0                           Kusum Healthcare, Иndiya  \n",
       "2                        Aburaihon Pharmaceutical Co  \n",
       "5                Psychotropics India Limited, Иndiya  \n",
       "6                                             BIOGEN  \n",
       "7                                             Сertus  \n",
       "...                                              ...  \n",
       "997                 Мega Лayfsaynsiz ЛТД, Аvstraliya  \n",
       "998   World Medicine Ilac San. Ve Tic. A.S. Тurtsiya  \n",
       "999   World Medicine Ilac San. Ve Tic. A.S. Тurtsiya  \n",
       "1000                        Kusum Healthcare, Иndiya  \n",
       "1002                               Зdorove , Уkraina  \n",
       "\n",
       "[812 rows x 4 columns]"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df3"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "50f9ff88",
   "metadata": {},
   "outputs": [],
   "source": [
    "# df1[['name', 'producer']] = df1[['name1', 'producer1']]\n",
    "# df3[['name', 'producer']] = df3[['name2', 'producer2']]\n",
    "# display(df1)\n",
    "# display(df3)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "e04480c3",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>name2</th>\n",
       "      <th>producer2</th>\n",
       "      <th>name1</th>\n",
       "      <th>price1</th>\n",
       "      <th>company1</th>\n",
       "      <th>producer1</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>L-Цет таб №100</td>\n",
       "      <td>Kusum Healthcare, Индия</td>\n",
       "      <td>L-Цет таб №100</td>\n",
       "      <td>143092.79</td>\n",
       "      <td>Wol</td>\n",
       "      <td>Kusum Healthcare, Индия</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Абинекс таб. 1 мг №8 (Каберголин)</td>\n",
       "      <td>Aburaihon Pharmaceutical Co</td>\n",
       "      <td>Абинекс таб. 1 мг №8 (Каберголин)</td>\n",
       "      <td>176300.00</td>\n",
       "      <td>Wol</td>\n",
       "      <td>Aburaihon Pharmaceutical Co</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Автория таб. 25 мг №30</td>\n",
       "      <td>Psychotropics India Limited, Индия</td>\n",
       "      <td>Автория таб. 25 мг №30</td>\n",
       "      <td>38790.00</td>\n",
       "      <td>Wol</td>\n",
       "      <td>Psychotropics India Limited, Индия</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Адазал сусп. 100мг/5мг.30мл №1</td>\n",
       "      <td>BIOGEN</td>\n",
       "      <td>Адазал сусп. 100мг/5мг.30мл №1</td>\n",
       "      <td>21999.00</td>\n",
       "      <td>Wol</td>\n",
       "      <td>BIOGEN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Адемта лиоф. д/и. 400мг/5мл №5</td>\n",
       "      <td>Сертус</td>\n",
       "      <td>Адемта лиоф. д/и. 400мг/5мл №5</td>\n",
       "      <td>316500.00</td>\n",
       "      <td>Wol</td>\n",
       "      <td>Сертус</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>813</th>\n",
       "      <td>Медитрол капс. 0,25 №30</td>\n",
       "      <td>Мега Лайфсайнсиз ЛТД, Австралия</td>\n",
       "      <td>Медитрол капс. 0,25 №30</td>\n",
       "      <td>57200.00</td>\n",
       "      <td>Wol</td>\n",
       "      <td>Мега Лайфсайнсиз ЛТД, Австралия</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>814</th>\n",
       "      <td>Медолопрам таб. 10 мг №28</td>\n",
       "      <td>World Medicine Ilac San. Ve Tic. A.S. Турция</td>\n",
       "      <td>Медолопрам таб. 10 мг №28</td>\n",
       "      <td>112850.00</td>\n",
       "      <td>Wol</td>\n",
       "      <td>World Medicine Ilac San. Ve Tic. A.S. Турция</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>815</th>\n",
       "      <td>Медотилин капс. 400 мг №14</td>\n",
       "      <td>World Medicine Ilac San. Ve Tic. A.S. Турция</td>\n",
       "      <td>Медотилин капс. 400 мг №14</td>\n",
       "      <td>92900.00</td>\n",
       "      <td>Wol</td>\n",
       "      <td>World Medicine Ilac San. Ve Tic. A.S. Турция</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>816</th>\n",
       "      <td>Мезакар таб. 200 мг №50</td>\n",
       "      <td>Kusum Healthcare, Индия</td>\n",
       "      <td>Мезакар таб. 200 мг №50</td>\n",
       "      <td>34000.00</td>\n",
       "      <td>Wol</td>\n",
       "      <td>Kusum Healthcare, Индия</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>817</th>\n",
       "      <td>Мезатон р-р. 10мг/мл 1мл амп. №10</td>\n",
       "      <td>Здоровье , Украина</td>\n",
       "      <td>Мезатон р-р. 10мг/мл 1мл амп. №10</td>\n",
       "      <td>12230.00</td>\n",
       "      <td>Wol</td>\n",
       "      <td>Здоровье , Украина</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>818 rows × 6 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                                 name2  \\\n",
       "0                       L-Цет таб №100   \n",
       "1    Абинекс таб. 1 мг №8 (Каберголин)   \n",
       "2               Автория таб. 25 мг №30   \n",
       "3       Адазал сусп. 100мг/5мг.30мл №1   \n",
       "4       Адемта лиоф. д/и. 400мг/5мл №5   \n",
       "..                                 ...   \n",
       "813            Медитрол капс. 0,25 №30   \n",
       "814          Медолопрам таб. 10 мг №28   \n",
       "815         Медотилин капс. 400 мг №14   \n",
       "816            Мезакар таб. 200 мг №50   \n",
       "817  Мезатон р-р. 10мг/мл 1мл амп. №10   \n",
       "\n",
       "                                        producer2  \\\n",
       "0                         Kusum Healthcare, Индия   \n",
       "1                     Aburaihon Pharmaceutical Co   \n",
       "2              Psychotropics India Limited, Индия   \n",
       "3                                          BIOGEN   \n",
       "4                                          Сертус   \n",
       "..                                            ...   \n",
       "813               Мега Лайфсайнсиз ЛТД, Австралия   \n",
       "814  World Medicine Ilac San. Ve Tic. A.S. Турция   \n",
       "815  World Medicine Ilac San. Ve Tic. A.S. Турция   \n",
       "816                       Kusum Healthcare, Индия   \n",
       "817                            Здоровье , Украина   \n",
       "\n",
       "                                 name1     price1 company1  \\\n",
       "0                       L-Цет таб №100  143092.79      Wol   \n",
       "1    Абинекс таб. 1 мг №8 (Каберголин)  176300.00      Wol   \n",
       "2               Автория таб. 25 мг №30   38790.00      Wol   \n",
       "3       Адазал сусп. 100мг/5мг.30мл №1   21999.00      Wol   \n",
       "4       Адемта лиоф. д/и. 400мг/5мл №5  316500.00      Wol   \n",
       "..                                 ...        ...      ...   \n",
       "813            Медитрол капс. 0,25 №30   57200.00      Wol   \n",
       "814          Медолопрам таб. 10 мг №28  112850.00      Wol   \n",
       "815         Медотилин капс. 400 мг №14   92900.00      Wol   \n",
       "816            Мезакар таб. 200 мг №50   34000.00      Wol   \n",
       "817  Мезатон р-р. 10мг/мл 1мл амп. №10   12230.00      Wol   \n",
       "\n",
       "                                        producer1  \n",
       "0                         Kusum Healthcare, Индия  \n",
       "1                     Aburaihon Pharmaceutical Co  \n",
       "2              Psychotropics India Limited, Индия  \n",
       "3                                          BIOGEN  \n",
       "4                                          Сертус  \n",
       "..                                            ...  \n",
       "813               Мега Лайфсайнсиз ЛТД, Австралия  \n",
       "814  World Medicine Ilac San. Ve Tic. A.S. Турция  \n",
       "815  World Medicine Ilac San. Ve Tic. A.S. Турция  \n",
       "816                       Kusum Healthcare, Индия  \n",
       "817                            Здоровье , Украина  \n",
       "\n",
       "[818 rows x 6 columns]"
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df4 = pd.merge(df3, df1, how='left', on=['name_latin', 'producer_latin'])\n",
    "df4 = df4.drop(['name_latin','producer_latin'], axis=1)\n",
    "df4"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "63e62b52",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4877d06a",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
